name: Java CI with Docker # Navnet på workflowet

on:
  push:
    branches:
      - main # Udløses ved push til hovedgrenen (kan ændres efter behov)

jobs:
  build_and_deploy: # Definerer et job kaldet 'build_and_deploy'
    runs-on: ubuntu-latest # Jobbet køres på den seneste version af Ubuntu

    steps:
      - name: Checkout code # Tjekker koden ud fra GitHub repository
        uses: actions/checkout@v2

      - name: Set up JDK 17 # Opsætter Java Development Kit (JDK) version 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt' # Bruger AdoptOpenJDK distribution

      - name: Build with Maven # Bygger projektet ved hjælp af Maven
        run: mvn -B package --file pom.xml # Maven kommando til at pakke applikationen

      - name: Run tests # Kører enhedstests
        run: mvn test # Maven kommando til at køre tests

      - name: Build Docker Image # Bygger Docker-billedet for applikationen
        run: docker build -t myapp:latest . # Docker kommando til at bygge billedet

      - name: Login to Azure # Logger ind på Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_CONNECTION_NAME }} # Bruger Azure Service Connection

      - name: Push Docker Image to Azure Container Registry # Pusher Docker-billedet til Azure Container Registry
        run: |
          docker tag myapp:latest myacr.azurecr.io/myapp:latest
          docker push myacr.azurecr.io/myapp:latest

      - name: Deploy to Azure Web App # Deployerer til Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myapp' # Navnet på Azure Web App
          images: 'myacr.azurecr.io/myapp:latest' # Specifikation af Docker-billedet
